/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ijkjtvzaphfhnvgacygn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqa2p0dnphcGhmaG52Z2FjeWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzkwNjcsImV4cCI6MjA4ODI1NTA2N30.7x1XxXqRQS3dPWH5wAo7-0RQsbYbISsVGhtbyrW5P-o"